### ISSUE TITLE
phet

### ISSUE THREAD

**Issue by phettest02** [phettestbpt11/bot-1#3]
Build version: v.4.8.0 
Build date: 1979-11-30 00:00:00 
Current date: 2017-04-07 15:54:50 
Device: LAVA iris 810 

Stack trace:  
java.lang.NullPointerException: Attempt to write to field 'java.lang.String com.alorma.github.sdk.bean.dto.request.IssueRequest.milestoneName' on a null object reference
	at com.alorma.github.ui.activity.NewIssueActivity.createIssue(NewIssueActivity.java:299)
	at com.alorma.github.ui.activity.NewIssueActivity.onOptionsItemSelected(NewIssueActivity.java:266)
	at android.app.Activity.onMenuItemSelected(Activity.java:2940)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:408)
	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:198)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:107)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:107)
	at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:206)
	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:777)
	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:817)
	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:964)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:954)
	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
	at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:157)
	at android.view.View.performClick(View.java:4848)
	at android.view.View$PerformClick.run(View.java:20262)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5631)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by phettest02** [comment]
#on

**Comment by phettest02** [comment]
http://line.me/ti/p/Bm8Gkr8jsz
